sudo: false
dist: trusty
language: php

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - github_token:
        secure: "GrPeKimeHRXL7Bl1ORmmnbKRBsJP/c3kfuK9+KjfjuJYLXQDjar1duVzLLG3ErjFdas0H5W8stNi/120XH8/fwIK/PCjr828cGIkqzkV1hXbj8uWKnf3O8unxwzAyMCQNXjsmcQA0ubxTzxkgJXfWzNtwHYv/dVvu8aq5KrdOGWKBjyiqAFX7tb7/NoINrqr1CkmRvq4V4sPoErpUT0VMmptTmFfx5XY3XngkbMiRWpJR1Fjqvx3FnN65EXi0/jZ2LJSmqdPM41O0WZv0TwoR5gjsC/YF0QqFrYHAEJsiEbkmVgn9fTx/qrW+wJqsCDy3O9sGr749nNb6/qy7+2hsenAiZeTFU7J0dJCo4B1+OZOP6aFU+sGDlXzZaStydOR+p7jfizq2W1imlaZ7nybqzZTO78Yui+NP+UWOB5TQsJkjVa2XaVkLV7UCTE8a8omnVcoQ2RGgRNQl5FwxFLq6UjqerxLp1ftyGDLDHdg8gwTt5GT+e+ucUC5SRAQDzMeIaKkcAddH/dYKd8+cD3+h1eN6DUPwKV9Gh5SpDG19ndJDlrVAnqe36C4sjGf2+D8W06T8b4sVwkZvWIXJT1voHwJI4bkGM6xvfGqMuDwFRY5EMDke2PRsbCqPoWAhOfY97KA7CoQn6n1ze/wpJu2qOiMcU52TiXkdTB6nmZMtYk="
matrix:
  allow_failures:
    - stage: acceptance-test
  include:
  - php: 5.6
    if: type != cron
  - php: 7.0
    if: type != cron
  - php: 7.1
    if: type != cron

  - stage: validator-test
    if: type != cron
    php: 7.1
    before_script:
      - pip install --user bs4
      - bash .bin/generate-release-package.sh
      - travis_retry composer require --dev $COMPOSER_ARGS codeception/codeception
    script:
      - bash .bin/run-validator-test.sh
    after_script: skip


install:
  - travis_retry composer require --dev $COMPOSER_ARGS
  - travis_retry composer install $COMPOSER_ARGS
  - composer show
script:
  - composer test-coverage
  - composer cs-check

after_script:
   - travis_retry composer upload-coverage

before_deploy:
  - export REPO_NAME=`echo $TRAVIS_REPO_SLUG | awk -F'/' '{print $2}'`
  - export RELEASE_NOTES=$(composer make-release-notes)
  - bash .bin/generate-wiki-notes.sh
  - bash .bin/generate-readme-badge.sh
  - bash .bin/generate-release-package.sh $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: YI7sUrfMyKyJD60kElGkO7yBDkGEh+069yS8bFAIDUST7s48J+dDP/r2G9dN9oQwhs9hvNjpNytpZDPys838T+Z0mNtFZ9Wu022hV3MpbKUuMl7L9P0MQQmxjg4bKyKK3Hl9tPrZ3UsKRlwIUmRGGYQ7cjs4zumorqs19YsB3X+WnnxAmmYB3kHQYfNKgVnmcG2QHJyx5KaLZ0EsWynSHXkYb8bVCtdlbQFNnpChvGHPprZrHAszLCYnlU7AEZGdbuk17oIfXO9Wjuu1GV8iJ2VgKkTCzW4FBC5eHJyZezojPFUm1I5tvdihRZuyBekVGOF23J6pvHLqPx77clT+/Vn6T+UMDuh1INZ0LKt4UOU42oEDKGblWZx2VYWcHwfEK+ckJWZkT9EBfg/CMenJly2tbtBj6++XNvxgGEDn6XqKIEatcb7X/aiy4f8BPXa3/pzgZAlvzZbGGqHFNZPAlgcXBBXgbaC7VvMhvi6Z5AG5ylKzPS5GCD95ozPC+cGv0234TBJus5oZck4qNiT53IUQ7Ta+OGVB0Mea105VAoQI0I7YcgaqW6c4h2YTmnuuQsIzAwPOrJ5TAinj8Z8mZ9C11tEcNF3Pgy1tOoG/YLurhOJm7v1ebotRb/DIeSHU8RfNatnDSSky4YS6Y8k2pQthdC9m7m2f2mJYuGdLjlM=
  file: wirecardpaymentgateway.zip
  body: "${RELEASE_NOTES}"
  skip_cleanup: true
  on:
    repo: ${TRAVIS_REPO_SLUG}
    tags: true

notifications:
  email: false
  slack:
    rooms:
      secure: YI7sUrfMyKyJD60kElGkO7yBDkGEh+069yS8bFAIDUST7s48J+dDP/r2G9dN9oQwhs9hvNjpNytpZDPys838T+Z0mNtFZ9Wu022hV3MpbKUuMl7L9P0MQQmxjg4bKyKK3Hl9tPrZ3UsKRlwIUmRGGYQ7cjs4zumorqs19YsB3X+WnnxAmmYB3kHQYfNKgVnmcG2QHJyx5KaLZ0EsWynSHXkYb8bVCtdlbQFNnpChvGHPprZrHAszLCYnlU7AEZGdbuk17oIfXO9Wjuu1GV8iJ2VgKkTCzW4FBC5eHJyZezojPFUm1I5tvdihRZuyBekVGOF23J6pvHLqPx77clT+/Vn6T+UMDuh1INZ0LKt4UOU42oEDKGblWZx2VYWcHwfEK+ckJWZkT9EBfg/CMenJly2tbtBj6++XNvxgGEDn6XqKIEatcb7X/aiy4f8BPXa3/pzgZAlvzZbGGqHFNZPAlgcXBBXgbaC7VvMhvi6Z5AG5ylKzPS5GCD95ozPC+cGv0234TBJus5oZck4qNiT53IUQ7Ta+OGVB0Mea105VAoQI0I7YcgaqW6c4h2YTmnuuQsIzAwPOrJ5TAinj8Z8mZ9C11tEcNF3Pgy1tOoG/YLurhOJm7v1ebotRb/DIeSHU8RfNatnDSSky4YS6Y8k2pQthdC9m7m2f2mJYuGdLjlM=
    template:
      - "%{repository}#%{build_number} (%{branch} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    on_success: change
    on_failure: change