version: '3'
services:
# Reference: https://hub.docker.com/_/mysql
  prestashop.database:
    container_name: prestashop-database
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=prestashop
    networks:
      - prestashop-net
    command:
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
      - "--default-authentication-plugin=mysql_native_password"

# Default admin credentials:
# demo@prestashop.com ; prestashop_demo
# Reference: https://hub.docker.com/r/prestashop/prestashop
  prestashop.web:
    container_name: "${PRESTASHOP_CONTAINER_NAME}"
    build:
      context: .
    environment:
      - DB_SERVER=prestashop-database
      - DB_PASSWD=supersecret
      - DB_NAME=prestashop
      - PS_INSTALL_AUTO=1
      - PS_FOLDER_ADMIN=backend
      - PS_DOMAIN="${PRESTASHOP_CONTAINER_DOMAIN}"
      - PS_SHOP_URL="${PRESTASHOP_CONTAINER_SHOP_URL}"
      - PS_FOLDER_INSTALL=removedinstall
      - SSL=1
    networks:
      - prestashop-net
    ports:
      - "8080:80"
    depends_on:
      - prestashop.database

# Setup container network, this allows for mysql to be unavailable for the www
networks:
  prestashop-net: